package org.evd.game.gencode;


import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import javax.tools.StandardLocation;
import java.io.File;
import java.io.IOException;
import java.util.Set;

public abstract class ProcessorBase extends AbstractProcessor {
    /** Element操作类 */
    protected Elements elementUtils;
    /** 类信息工具类 */
    protected Types typeUtils;
    /** 日志工具类 */
    protected Messager messager;
    /** 文件创建工具类 */
    protected Filer filer;

    public String getGenPath(String packageName, String className) {
        String rootPath = getProjectRootPackagePath(className);
        String packagePath = packageName.replaceAll("\\.", File.separator + File.separator);

        String path = rootPath + File.separator + packagePath + File.separator;
        println("targetPath: " + path);

        return path;
    }

    public String getProjectRootPackagePath(String className) {
        // 创建一个java类，但没真正写到磁盘，从javaFile中获得路径
        JavaFile jf = JavaFile.builder("", TypeSpec.classBuilder(className).build())
                .addFileComment("This file is generated by program. Do not edit it manually")
                .indent("    ")
                .build();

        try {
            String path = null;
            path = filer.getResource(StandardLocation.SOURCE_OUTPUT, jf.packageName, className).toUri().toString();
            path = path.split("/build/")[0].split("///")[1];

            AptUtils.StringExt stringExt = new AptUtils.StringExt();
            stringExt.appendJoin(path)
                    .appendJoin("src")
                    .appendJoin("gen")
                    .appendJoin("java");

            return stringExt.toString();

        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        elementUtils = processingEnv.getElementUtils();
        typeUtils = processingEnv.getTypeUtils();
        messager = processingEnv.getMessager();
        filer = processingEnv.getFiler();

        init();
    }

    /**
     * 指明有哪些注解需要被扫描到，返回注解的全路径（包名+类名）
     */
    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return supportAnnotation();
    }

    protected abstract Set<String> supportAnnotation() ;

    /**
     * 用来指定当前正在使用的Java版本，一般返回SourceVersion.latestSupported()表示最新的java版本即可
     */
    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public final boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (annotations == null || annotations.isEmpty()) return false;
        gen(annotations, roundEnv);
        return false;
    }

    protected void println(String str){
        messager.printMessage(Diagnostic.Kind.NOTE, str);
    }

    protected abstract void init();
    protected abstract void gen(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv);
}
